M48
; DRILL file {KiCad 7.0.8} date Mi 22 Nov 2023 15:29:50 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-22T15:29:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X7.2993Y-7.2993
X7.2993Y-10.4172
X10.4172Y-7.2993
X10.4172Y-10.4172
T0
M30
