M48
; DRILL file {KiCad 7.0.8} date Mi 15 Nov 2023 20:37:27 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-15T20:37:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X7.1323Y-7.1323
X7.1323Y-10.5843
X10.5843Y-7.1323
X10.5843Y-10.5843
T0
M30
